import type { Metadata } from "next";
import Sidebar from '../components/ui/sidebar';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900`}
      >
 
        <nav className="p-4 text-white">
          <Link href="/" className="mr-4">Home</Link>
          <Link href="/uploadtest">Upload</Link>
        </nav>       
        {children}
      </body>
    </html>
  );
}
