import type { Metadata } from "next";
import Sidebar from "../components/ui/sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Amplify } from "aws-amplify";
import awsConfig from "@/lib/aws-exports";

import TopNavbar from "@/components/topNavbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure Amplify once at the root
Amplify.configure(awsConfig as any);

export const metadata: Metadata = {
  title: "Funnels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <TopNavbar />
        <section className="mt-16 w-full">{children}</section>
      </body>
    </html>
  );
}
